### ISSUE TITLE
ArgumentNullException from AddTransitionFromAny shortcut method

### ISSUE THREAD

**Issue by stevewoolcock** [Inspiaaa/UnityHFSM#10]
An `ArgumentNullException` is thrown when using the `AddTransitionFromAny(to, condition, forceInstantly)` shortcut extension method for FSMs where `TStateId` is a `string` type.

This occurs because the extension method passes `default` through to `CreateOptimizedTransition()`, where the default value for a string is null. I'm not sure there's a 'clean' way to fix this, other than adding string-specific extension method variants.

```
ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <cdc4992cc04a4e77a24a09cd121af77b>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <cdc4992cc04a4e77a24a09cd121af77b>:0)
FSM.StateMachine`3[TOwnId,TStateId,TEvent].GetOrCreateStateBundle (TStateId name) (at Assets/_Game/Scripts/Salvage.Core/Runtime/HFSM/StateMachine.cs:322)
FSM.StateMachine`3[TOwnId,TStateId,TEvent].AddTransition (FSM.TransitionBase`1[TStateId] transition) (at Assets/_Game/Scripts/Salvage.Core/Runtime/HFSM/StateMachine.cs:368)
FSM.StateMachineShortcuts.AddTransitionFromAny[TOwnId,TStateId,TEvent] (FSM.StateMachine`3[TOwnId,TStateId,TEvent] fsm, TStateId to, System.Func`2[T,TResult] condition, System.Boolean forceInstantly) (at Assets/_Game/Scripts/Salvage.Core/Runtime/HFSM/StateMachineShortcuts.cs:84)
```

**Comment by stevewoolcock** [comment]
The following extension method would resolve this problem for FSMs with string state IDs:
```cs
public static void AddTransitionFromAny<TOwnId, TEvent>(
	this StateMachine<TOwnId, string, TEvent> fsm,
	string to,
	Func<Transition<string>, bool> condition = null,
	bool forceInstantly = false)
{
	fsm.AddTransition(CreateOptimizedTransition(string.Empty, to, condition, forceInstantly));
}
```

**Comment by Inspiaaa** [comment]
Thanks a lot for reporting the bug and your detailed report with a solution proposal. 👍 

@mfandreich had a very clean solution to this problem. I have not not merged his solution yet, because it is part of a larger pull request that I‘m working on. If you need a quick fix in the meantime, please see https://github.com/Inspiaaa/UnityHFSM/pull/9/commits/f68818f764b3af869db144398d38aebbcb7dd5b2
