### ISSUE TITLE
How can I see the current state of the state machine for debugging?

### ISSUE THREAD

**Issue by wilg** [Inspiaaa/UnityHFSM#15]
I was hoping for a method that would output a string representing the nested state such as `Patrol.Move.SearchForPOI`?

**Comment by leehiroshi** [comment]
Hi，do you find a solution to this？

**Comment by Monsoonexe** [comment]
Yes. I used the fsm.ActiveState property.

**Comment by wilg** [comment]
I switched to https://github.com/ashblue/fluid-behavior-tree

**Comment by Inspiaaa** [comment]
Hi @wilg,
apologies for the late reply. I know you have moved on to another library, but for closure let me answer the original question all the same.
In the current version there is no way to get a string representation of the active nested state.
I agree that it would be a useful feature and for this reason I have implemented it in the `release` branch, which will finally lead to the `1.10` release. If you find yourself coming back to UnityHFSM, please take a look at the `Changelog.md` and the `TestActiveHierarchyPath.cs` files for usage examples.

**Comment by Inspiaaa** [comment]
This feature is now part of the recent 2.0 release.
