### ISSUE TITLE
feature request:  OnActiveStateChanged event?

### ISSUE THREAD

**Issue by santutu** [Inspiaaa/UnityHFSM#22]
I suggest to add an Active StateChanged event to StateMachine class to track the state.
I took a quick look at the code, and I think it would be possible by invoking the event at StateMachine's ChangeState method.  if this function  is ok, I am willing to do pull request.

simple example
fsm.OnActiveStateChanged += (activeState)=> Debug.Log(activeState);

**Comment by Monsoonexe** [comment]
This event sounds pretty useful.

**Comment by Inspiaaa** [comment]
Hi @santutu,
Thanks for the feature request and the implementation of it in your pull request! I especially appreciate that you added unit tests. Thanks a lot!

I have merged your PR and made a few small changes. It will be released with the upcoming 2.1 version.

As I have not encountered a real-world use case for this feature myself, I'll be rolling out this feature conservatively, starting with a minimal version and seeing how well it fares. Future versions may then include enhancements, once I know more about how this feature is used.

**Comment by woodward54** [comment]
+1, this feature would also be useful for my project

**Comment by Inspiaaa** [comment]
The "state changed" event is now available in the latest release ([2.1](https://github.com/Inspiaaa/UnityHFSM/releases/tag/v2.1.0)) :+1:

**Comment by woodward54** [comment]
Thank you! @Inspiaaa
