### ISSUE TITLE
Name of Test asmdef can conflict with project

### ISSUE THREAD

**Issue by Faimen** [Inspiaaa/UnityHFSM#25]
Default name is Tests, can conflict with project, if you've another Test asmdef defined for your game before
I think it's must be, UnityHFSM.Tests

**Comment by Inspiaaa** [comment]
Hi @Faimen,
thanks for bringing this to my attention. That's a good catch!
As you can see, I've implemented your proposal in a recent commit which is part of the upcoming 2.0 release.
