### ISSUE TITLE
Documentation request: Explain what HybridStateMachine is

### ISSUE THREAD

**Issue by rafaeldolfe** [Inspiaaa/UnityHFSM#31]
Just reading through the 2.0 changelog! I don't grasp exactly what the HybridStateMachine is. It seems simply like an improved version of the normal StateMachine class? It would be greatly appreciated to see some documentation on the HybridStateMachine, explaining what's different about it and what its functionality is.

**Comment by Inspiaaa** [comment]
Hi @rafaeldolfe,

Thanks for the suggestion! I have now written a wiki entry for the `HybridStateMachine` class that you can read [here](https://github.com/Inspiaaa/UnityHFSM/wiki/Hybrid-State-Machines). For a real-world usage example you can also take a look at the advanced guard AI tutorial [here](https://github.com/Inspiaaa/UnityHFSM/wiki/Advanced-Tutorial:-Guard-AI).
