### ISSUE TITLE
Sample code can not compile in version 2.0

### ISSUE THREAD

**Issue by 1174331877** [Inspiaaa/UnityHFSM#32]
![image](https://github.com/Inspiaaa/UnityHFSM/assets/30250246/5b1344a6-b0e2-4cc5-9eaf-ac11e98b58ad)

**Comment by reimzm** [comment]
![Snipaste_2023-10-12_16-11-25](https://github.com/Inspiaaa/UnityHFSM/assets/81622515/76bdd0a0-22a3-4aaf-8822-430cc6909e92)

**Comment by Inspiaaa** [comment]
Hi @1174331877,
thanks a lot for bringing this to my attention! I had not realised both of the built-in samples currently do not compile. Sorry for the inconvenience.
I have worked on a fix and just released it in the 2.0.1 release.
