### ISSUE TITLE
Mention Support for Generic State Identifiers Higher Up in README 

### ISSUE THREAD

**Issue by sandsalamand** [Inspiaaa/UnityHFSM#33]
Since this is something that should be done early to avoid having to rewrite a lot of code, I think it would be good to at least put a little hint higher up in the README that you're allowed to do this. I just saw this feature while looking for something more complex after already creating a bunch of states using strings. It's not a big deal to refactor, but I think it might save people time in the future if this was changed.

**Comment by Inspiaaa** [comment]
Hi @sandsalamand,
thanks for the suggestion. I've added a hint regarding this in the `Adding states` section of the first example.
