### ISSUE TITLE
[Question] Any node editor for UnityHfsm?Or other Editor Tool ?

### ISSUE THREAD

**Issue by mi1890** [Inspiaaa/UnityHFSM#37]
I think it's more intuitional to use tool to create a fsm than to use code.
So is there any editor tool for UnityHFSM?

**Comment by Inspiaaa** [comment]
Hi @mi1890,
UnityHFSM is a primarily code-driven library and does not come with a visual editor / interface out of the box. 
Theoretically a visual editor could be built around UnityHFSM, but this is not part of the current roadmap.

If your occasionally interested in visualising more than interactively creating state machines, I personally find myself using [Mermaid](https://mermaid.js.org/) to illustrate the state machines I've created or plan to create.
