### ISSUE TITLE
I think you should create a demo scene

### ISSUE THREAD

**Issue by kamike** [Inspiaaa/UnityHFSM#6]
I found a lot of state machine-related projects, and found that this library is still the best, but there are no Issues, and there are too few stars. I should write more examples.

**Comment by shiena** [comment]
I have added a demo scene using EnemyController from README to the upm samples in #3. The demo scene will be available as soon as the PR is merged. If you want to use the upm package right away, add the following git url.
https://github.com/shiena/UnityHFSM.git#feature/support-upm
